<?php
set_include_path( get_include_path() . PATH_SEPARATOR . $_SERVER['DOCUMENT_ROOT'] );
date_default_timezone_set('America/Detroit');
?>

<!doctype html>
<html lang="en-US">
  <!-- generated by uswds@2.7.0 -->
  <head>
    <?php
      include("assets/includes/meta.inc");
    ?>
    <title>Something didn't work</title>
    <link rel="stylesheet" href="https://www.historicallyfamouslighthouses.com/assets/uswds/css/uswds.min.css">
    <link rel="stylesheet" href="https://www.historicallyfamouslighthouses.com/assets/css/omid.css">
  </head>
  <body>
    <?php
      include("assets/includes/banner.inc");
      include("assets/includes/header-others.inc");
      include("assets/includes/main-error.inc");
      include("assets/includes/footer.inc");
      include("assets/includes/scripts.inc");
    ?>
  </body>
</html>