<a class="usa-skipnav" href="#main-content">Skip to main content</a>
    <section class="usa-banner" aria-label="Lighthouses and You - A Government IT Modernization Story">
      <div class="usa-accordion">
        <header class="usa-banner__header">
          <div class="usa-banner__inner">
            <div class="grid-col-auto">
              <img class="usa-banner__header-flag" src="<?php echo $path;?>assets/uswds/img/us_flag_small.png" alt="U.S. flag">
            </div>
            <div class="grid-col-fill tablet:grid-col-auto">
              <p class="usa-banner__header-text">This is NOT an official US website, but one made by Omid</p>
              <p class="usa-banner__header-action" aria-hidden="true">Here’s how you know</p>
            </div>
            <button class="usa-accordion__button usa-banner__button"
              aria-expanded="false" aria-controls="gov-banner">
              <span class="usa-banner__button-text">Here’s how you know</span>
            </button>
          </div>
        </header>
        <div class="usa-banner__content usa-accordion__content" id="gov-banner">
          <div class="grid-row grid-gap-lg">
            <div class="usa-banner__guidance tablet:grid-col-6">
              <img class="usa-banner__icon usa-media-block__img" src="<?php echo $path;?>assets/uswds/img/icon-dot-gov.svg" alt="Dot gov">
              <div class="usa-media-block__body">
                <p>
                  <strong>The fact there is no *.gov is a big tip off.</strong>
                  <br>
                  Any website that claims to be a government one should use *.gov. Even though not all do, before you ever share personal information, make sure you’re on a real government website.
                </p>
              </div>
            </div>
            <div class="usa-banner__guidance tablet:grid-col-6">
              <img class="usa-banner__icon usa-media-block__img" src="<?php echo $path;?>assets/uswds/img/icon-https.svg" alt="Https">
              <div class="usa-media-block__body">
                <p>
                  <strong>The site is secure, though.</strong>
                  <br>
                  The <strong>https://</strong> ensures that you are connecting to my website and that any information you provide is encrypted and transmitted securely. I use <a href="https://letsencrypt.org/" alt="Let's Encrypt's official website." target="_blank" rel="noopener noreferrer">LetsEncrypt</a>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>