<footer class="usa-footer">
      <div class="grid-container usa-footer__return-to-top">
        <a href="#">Return to top</a>
      </div>
      <div class="usa-footer__primary-section">
        <nav class="usa-footer__nav" aria-label="Footer navigation">
          <ul class="grid-row grid-gap">
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>" alt="The home page and where you can find out more about this website.">Home Page</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>lighthouses/" alt="A listing of all the nationally recognized historically famous lighthouses.">Lighthouses</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="<?php echo $path;?>resources/" alt="Various resources I found or would probably have found to be helpful when I was in the government.">Resources</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="https://www.ghaffaritabrizi.com/" alt="The personal webpage of the author of this website.">Omid's Website</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="https://github.com/oghaffari/historicallyfamouslighthouses.com/" alt="A link to the GitHub repository for this website." target="_blank" rel="noopener noreferrer">Repo</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="usa-footer__secondary-section">
        <div class="grid-container">
          <div class="grid-row grid-gap">
            <div class="usa-footer__logo grid-row mobile-lg:grid-col-6 mobile-lg:grid-gap-2">
              <div class="mobile-lg:grid-col-auto">
                <img class="usa-footer__logo-img footer-circle" src="<?php echo $path;?>assets/images/profile.png" alt="A picture of the old United States Light House Service.">
                <!-- Profile courtesy of Wikipedia - https://en.wikipedia.org/wiki/File:Seal_of_the_United_States_Lighthouse_Service.png -->
              </div>
              <div class="mobile-lg:grid-col-auto">
                <h3 class="usa-footer__logo-heading">Historically Famous Lighthouses</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>