<div class="usa-overlay"></div>
  <header class="usa-header usa-header--basic usa-header--megamenu">
    <div class="usa-nav-container">
      <div class="usa-navbar">
        <div class="usa-logo" id="basic-mega-logo">
          <em class="usa-logo__text"><a href="<?php echo $path;?>" title="Home" aria-label="Home">Historic Lighthouses</a></em>
        </div>
        <button class="usa-menu-btn">Menu</button>
      </div>
      <nav aria-label="Primary navigation" class="usa-nav">
        <div class="usa-nav__inner">
          <button class="usa-nav__close"><img src="<?php echo $path;?>assets/uswds/img/close.svg" alt="close"></button>
          <ul class="usa-nav__primary usa-accordion">
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>" alt="The home page and where you can find out more about this website."><span>Home</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>lighthouses/" alt="A listing of all the nationally recognized historically famous lighthouses."><span>Lighthouses</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="<?php echo $path;?>resources/" alt="Various resources I found or would probably have found to be helpful when I was in the government."><span>Resources</span></a></li>
          </ul>
        </div>
      </nav>
    </header>