<main id="main-content">
      <!-- Hero -->
      <!-- Image courtesy of Wikimedia Commons - https://commons.wikimedia.org/wiki/File:ME_-_Portland_Head_Light_-_Cape_Elizabeth_ME_03.jpg -->
      <section class="usa-hero" aria-label="Introduction">
        <div class="grid-container">
          <div class="usa-hero__callout">
            <h1 class="usa-hero__heading"><span class="usa-hero__heading--alt">Do your part:</span>
            </h1><p>If you want to care for - or even live in! - a lighthouse, <a href="https://www.volunteer.gov/" alt="The Volunteer.gov homepage." target="_blank" rel="noopener noreferrer">Volunteer.gov</a> has a ton of opportunities.</p><a class="usa-button" href="https://www.volunteer.gov/s/global-search/lighthouse" alt="The Center for Creative Education's donation page." target="_blank" rel="noopener noreferrer">Search lighthouses now!</a>
          </div>
        </div>
      </section>

      <!-- What's going on here -->
      <section class="grid-container usa-section">
        <div class="grid-row grid-gap">
          <div class="tablet:grid-col-4">
            <h2 class="font-heading-xl margin-top-0 tablet:margin-bottom-0">Government IT Modernization in One Site</h2>
          </div>
          <div class="tablet:grid-col-8 usa-prose">
            <p>One of the best things about working for the U.S. federal government is that you will eventually find out that you can not only visit historic lighthouses, but you may also be able to <a href="https://disposal.gsa.gov/s/lighthouseprogram" target="_blank" rel="noopener noreferrer">buy a lighthouse</a> for your post-government life as well. The lighthouses listed on this page are historically significant and are listed in the Coast Guard's world-famous booklet (what do you mean you haven't heard of it?) that goes by the compelling title of CG-232.</p>
            <p>The most recent version (<a href="https://media.defense.gov/2017/Jul/03/2001772530/-1/-1/0/H_FAMOUSLIGHTHOUSES.PDF" alt="The most recent version of CG-232." target="_blank" rel="noopener noreferrer">PDF</a>), which includes information on the last human-serviced lighthouse in service today, is what this site uses as data. The pictures, though, are from an older version (<a href="http://www.npshistory.com/publications/cg-232.pdf" alt="The most recent version of CG-232." target="_blank" rel="noopener noreferrer">PDF</a>), when there were still 158 human-serviced lighthouses. For whatever reason, the new version didn't include photos, so I wanted to not only fix that problem but also link the lighthouses themselves to other government services and useful links you can enjoy if you visit them!</p>
            <p>If you're curious about other reasons behind why I put this site together, I came up with a few other things I'm hoping people take away from this site beyond how cool the people who take care of our nation's lighthouses are for what they do. See if any of them resonate!</p>
          </div>
        </div>
      </section>

      <!-- 4 highlights -->
      <section class="usa-graphic-list usa-section usa-section--dark">
        <div class="grid-container">
          <div class="usa-graphic-list__row grid-row grid-gap">
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/punctuality.png" alt="Icon of a watch created by Freepik on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">I did this in a few hours.</h2>
                <p>Even though many in the government could do it faster and better, it isn't so easy. There are security and legal reviews even for a simple site like this.</p>
              </div>
            </div>
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/contract.png" alt="Icon of a Contract created by Freepik on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">It would need agreements.</h2>
                <p>GSA's TTS would probably build the site, the US Coast Guard would provide details on the lighthouses, and USDA would manage public visits to them.</p>
              </div>
            </div>
          </div>
          <div class="usa-graphic-list__row grid-row grid-gap">
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/broken.png" alt="Icon of broken monitors created by Freepik on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">The site could be orphaned.</h2>
                <p>Without funding, a dedicated team of either federal staff or contractors, and at least annual cybersecurity checks, this site would remain static.</p>
              </div>
            </div>
            <div class="usa-media-block tablet:grid-col">
              <img class="usa-media-block__img home-circle"  src="<?php echo $path;?>assets/images/technology.png" alt="Icon of a person using the latest technology created by Eucalyp on Flaticon.com.">
              <div class="usa-media-block__body">
                <h2 class="usa-graphic-list__heading">Modernization is a process.</h2>
                <p>More than just new tech, you have to get through the four As that get a plan to start and stick: Acquisitions, Agreements, Appropriations, ATOs.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="test-section-id" class="usa-section">
        <div class="grid-container">
          <h2 class="font-heading-xl margin-y-0">Got any ideas?</h2>
          <p class="usa-intro">How could we make something as simple as this a bit easier to make happen in the public sector? I love this stuff and would be happy to chat!</p>
          <a class="usa-button usa-button--big" href="https://www.linkedin.com/in/oghaffari/" alt="A link to my LinkedIn profile." target="_blank" rel="noopener noreferrer">Let's connect</a>
        </div>
      </section>
    </main>