<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>" alt="The home page and where you can find out more about this website.">Home</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>lighthouses/" alt="A listing of all the nationally recognized historically famous lighthouses.">Lighthouses</a></li>
                <li class="usa-sidenav__item"><a href="<?php echo $path;?>resources/" alt="Various resources I found or would probably have found to be helpful when I was in the government.">Resources</a></li>
              </ul>
            </nav>
          </div>
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Resources for the Civic Tech Fan</h1>
            <p class="usa-intro">Links to useful sites</p>
            <p>These are the things I used when I was in the government or found after leaving that I would have found useful had I seen them while still a civic servant. Here's to hoping it helps others! Note that everything is listed in alphabetical order.</p>
            <h2>Groups</h2>
            <p>
              <ul>
                <li><a href="https://opportunity.census.gov/coil/" alt="Official webpage of Census Open Innovation Labs (COIL)." target="_blank" rel="noopener noreferrer">Census Open Innovation Labs (COIL)</a></li>
                <li><a href="https://www.dhs.gov/pil" alt="Official webpage of the Department of Homeland Security Procurement Innovation Lab (DHS PIL)." target="_blank" rel="noopener noreferrer">Department of Homeland Security Procurement Innovation Lab (DHS PIL)</a></li>
                <li><a href="https://18f.gsa.gov/" alt="Official webpage of 18F." target="_blank" rel="noopener noreferrer">General Services Administration 18F</a></li>
                <li><a href="https://cic.gsa.gov/" alt="Official webpage of the General Services Administration Cloud Information Center." target="_blank" rel="noopener noreferrer">General Services Administration Cloud Information Center (GSA CIC)</a></li>
                <li><a href="https://fedsim.gsa.gov/" alt="Official webpage of FEDSIM." target="_blank" rel="noopener noreferrer">General Services Administration FEDSIM</a></li>
                <li><a href="https://www.irs.gov/newsroom/irs-creates-new-enterprise-digitalization-and-case-management-office-smith-abold-labreche-to-serve-as-co-directors" alt="Press release about the IRS Enterprise Digitalization and Case Management Office." target="_blank" rel="noopener noreferrer">Internal Revenue Service Enterprise Digitalization and Case Management Office</a> (press release only)</li>
                <li><a href="https://www.usds.gov/" alt="Official webpage of the U.S. Digital Service (USDS)." target="_blank" rel="noopener noreferrer">U.S. Digital Service (USDS)</a></li>
              </ul>
            </p>
            <h2>Resources</h2>
            <p>
              <ul>
                <li><a href="https://agilebudgeting.org" alt="The 18F created De-risking custom technology projects Playbooks." target="_blank" rel="noopener noreferrer">De-risking custom technology projects by 18F</a></li>
                <li><a href="https://playbook.cio.gov/" alt="The USDS created Digital Services Playbook." target="_blank" rel="noopener noreferrer">Digital Services Playbook by USDS</a></li>
                <li><a href="https://methods.18f.gov/" alt="The 18F created Methods." target="_blank" rel="noopener noreferrer">Methods by 18F</a></li>
                <li><a href="https://www.fai.gov/periodic-table/" alt="The Federal Acquisition Institute created Periodic Table of Innovations." target="_blank" rel="noopener noreferrer">Periodic Table of Innovations by the Federal Acquisition Institute</a></li>
                <li><a href="https://www.irs.gov/about-irs/procurement/about-pilot-irs" alt="The IRS created Pilot IRS." target="_blank" rel="noopener noreferrer">Pilot IRS by IRS</a></li>
                <li><a href="https://sitara.internetassociation.org" alt="The Internet Association created SITARA map." target="_blank" rel="noopener noreferrer">SITARA by Internet Association</a></li>
              </ul>
            </p>
          </main>
        </div>
      </div>
    </div>